- project/src/routes/(auth)/login/+page.svelte
> added api call sample

- .gitignore
- package-lock.json
- package.json
- src/routes/(auth)/login/+page.svelte
> The `localStorage.set` is undefined, please find alternative way of storing persistent data on client side. Consider Cookies maybe.
> added a response to the login using french-toast

- src/routes/(app)/+page.svelte
- src/routes/(auth)/login/+page.svelte
- the token now gets stored in the localStorage upon a successful login
- dashboard now checks if the access_token is present in the localStorage if not redirects the user to the login page
- added informative toasts using french-toast
> LEZZGOOWWW
> dasboard auth & token storage

- src/lib/session.js
- src/routes/(app)/+page.svelte
- the dashboard now validates the `access_token` if it exists in `localStorage` if now i will ask the user to login
- if the token is invalid it will try to generate a new one using the `refresh_token` if it exists in `localStorage`
- if the `refresh_token` is invalid the user will be prompted to login
> Token Auth and Generation Integrated

- src/routes/(app)/+page.server.js
- src/routes/(app)/+page.svelte
- src/routes/(auth)/login/+page.server.js
- src/routes/(auth)/login/+page.svelte
- src/routes/(auth)/oauth/+server.js
- google login now works for admin but still not fully implemented
- helpful responses
- token validation on `onMount`
> integrated google login

- src/routes/(app)/+page.svelte
- src/routes/(auth)/login/+page.server.js
> feat(auth): add a loading message while auth is ongoing

- src/routes/(app)/transactions/+page.svelte
> feat(transactions): make api call and parse the data

- src/routes/(app)/transactions/+page.svelte
This commits implement the edit feature in transactions
> feat(transactions): add edit feature

- src/routes/(app)/transactions/+page.svelte
This commit implements the delete feature by call the delete endpoint
> feat(transactions): add delete feature

- src/routes/(app)/create/[resident_id]/+page.server.js
- src/routes/(app)/create/[resident_id]/+page.svelte
- src/routes/(app)/resident-db/+page.svelte
- tailwind.config.js
this  commit makes the edit ui easy to integrate but pulling the data from the api
> feat(resident_data): make api call to pull resident data

- src/routes/(app)/create/[resident_id]/+page.svelte
This commit fixed the mistake in the request body of the api call
> fix(resident_db): fix the api call

- src/components/Radio.svelte
- src/routes/(app)/create/+page.svelte
- svelte.config.js
This commit implements the needed api call and value binding to make the form send the request to the endpoint
- the password validation does not match the password validation in the backend (this could raise confusion)
- the radio style should be update see the `src/components/Radio.svelte`
- the response from the api should be displayed to the user
> using neovim xD
> feat(accounts): integrate  user/employee account create

- .prettierrc
- src/routes/(app)/+page.svelte
- src/routes/(auth)/login-employee/+page.svelte
- src/routes/(auth)/login-user/+page.svelte
- src/routes/(auth)/login/+page.svelte
- src/routes/(user)/create-appointment/+page.svelte
This commit implements the necessary api calls along with value binding to allow user to create an appointment
- the ui still needs more styling
- we could further enhance it by adding more elements to the interface
> feat(user): implement api call for create appointment

- src/routes/(auth)/signup/+page.svelte
This commit implements the necessary api calls to allow a potential user to signup for an account.
> feat(signup): add user signup api call

- src/routes/(app)/+page.svelte
- src/routes/(app)/create-document/+page.svelte
- src/routes/(app)/documents/+page.svelte
- src/routes/(auth)/login-user/+page.svelte
- src/routes/(user)/+layout.svelte
- src/routes/(user)/status/+page.svelte
This commit implements all the necessary API calls to allow user to view and mark notifcations as read
This commit also formats the entire project
> feat(notification): add notification api call

- src/routes/(app)/+layout.svelte
- src/routes/(app)/+page.svelte
- src/routes/(app)/create/+page.svelte
- src/routes/(app)/dashboard/admin/+page.svelte
- src/routes/(app)/walk-in/+page.svelte
- src/routes/(user)/transaction/+page.svelte
This commit completes the 7 max api integration xD
> feat(dashboard): add helpful and entertaining info

- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
This commit fixes the navigation issue caused by missing referencing undefined function
> fix(dashboard): add missing form submit handler

- src/routes/dashboard/(user)/user/transactions/+page.svelte
This commit implements the necessary API calls to fetch the appointments that belong the current logged in user
> feat(user.appointments): add user appointments API call

- src/routes/dashboard/(admin)/admin/transactions/+page.svelte
- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
This commits add the necessary API calls to allow the admin to generate a document for the user from their transaction
This commit also implements auto download of the result
> feat(documents): add cert gen from appointment

- src/routes/dashboard/(admin)/admin/signup-approval/+page.svelte
This commit implements the necessary API calls to display the list of pending users and allow the admin to approve or reject them
> feat(user.pending): add user pending api call

- src/lib/session.js
- src/routes/(auth)/login-employee/+page.server.js
- src/routes/(auth)/login-employee/+page.svelte
- src/routes/(auth)/login-user/+page.server.js
- src/routes/(auth)/login-user/+page.svelte
- src/routes/(auth)/login/+page.server.js
- src/routes/(auth)/login/+page.svelte
- src/routes/(auth)/oauth/+server.js
- src/routes/(auth)/signup/+page.svelte
- src/routes/+layout.svelte
- src/routes/dashboard/(admin)/+layout.svelte
- src/routes/dashboard/(admin)/admin/create-document/+page.svelte
- src/routes/dashboard/(admin)/admin/create/+page.svelte
- src/routes/dashboard/(admin)/admin/create/[resident_id]/+page.svelte
- src/routes/dashboard/(admin)/admin/resident-db/+page.svelte
- src/routes/dashboard/(admin)/admin/signup-approval/+page.svelte
- src/routes/dashboard/(admin)/admin/transactions/+page.svelte
- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
- src/routes/dashboard/(admin)/employee/+page.svelte
- src/routes/dashboard/(user)/user/create-appointment/+page.svelte
- src/routes/dashboard/(user)/user/notifications/+page.svelte
- src/routes/dashboard/(user)/user/transactions/+page.svelte
- this commit implements the changes to the api endpoint
> feat: move to new api

- package-lock.json
- package.json
- src/routes/+page.svelte
- src/routes/dashboard/(admin)/admin/create-resident/+page.svelte
- src/routes/dashboard/(admin)/admin/transactions/+page.svelte
> feat: trying to pass the last test case

- src/routes/dashboard/(admin)/admin/transactions/+page.svelte
This commit fixes the regression introduced in 518cd15.
> fix(transactions): fix the table not reflecting the changes

- package-lock.json
yes, we care about security now. we are scared of hunkers xD.
> chore: security update

- src/routes/dashboard/(admin)/admin/create-resident/+page.svelte
- src/routes/dashboard/(admin)/admin/create/+page.svelte
This implements the requirements defined in #38.
> feat(resident, employee): better validation

- src/routes/dashboard/(admin)/admin/transactions/+page.svelte
wala nko gi change tong generate report sa taas kay ng wrong ato is ang test data man jud. So ang akoa lang gi change is ang naa sa table na part which is generate gi change nako as download para pud dili kaayo siya libog.
> feat(transaction): change "Generate" to "Download"

- src/routes/dashboard/(admin)/+layout.svelte
- src/routes/dashboard/(admin)/admin/resident-db/+page.svelte
This commit removes the create account button in resident database and replace it with Employee Accounts navigation item
> feat: move create account to sidebar

- src/routes/dashboard/(admin)/admin/create/+page.svelte
- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
This commit implements the period of residency input in walk-in page just like how it is implemented and add resident and create employee account.
> feat(walk-in): better period residency input

- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
This commit implements a feature that would allow an admin to select a resident in a dropdown and generate a certificate for them.
> feat(walk-in): add resident selector

- src/routes/dashboard/(admin)/admin/create-resident/+page.svelte
- src/routes/dashboard/(admin)/admin/create-resident/[resident_id]/+page.svelte
- src/routes/dashboard/(admin)/admin/create/+page.svelte
- src/routes/dashboard/(admin)/admin/create/[resident_id]/+page.svelte
- src/routes/dashboard/(admin)/admin/walk-in/+page.svelte
This commit adds the max attr to the input["date"] and set it to the current date to prevent the user form entering future dates.
> feat(walk-in,resident,employee): set max date to current date
